# Generated by Django 5.2.10 on 2026-01-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiodiversityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=100, verbose_name='nombre común')),
                ('scientific_name', models.CharField(blank=True, max_length=150, verbose_name='nombre científico')),
                ('category', models.CharField(choices=[('aves', 'Aves'), ('anfibios', 'Anfibios'), ('mamiferos', 'Mamíferos'), ('reptiles', 'Reptiles'), ('peces', 'Peces'), ('insectos', 'Insectos'), ('flora', 'Flora')], max_length=20, verbose_name='categoría')),
                ('description', models.TextField(verbose_name='descripción')),
                ('conservation_status', models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, verbose_name='estado de conservación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='biodiversity_animals_plants/', verbose_name='imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Entrada de Biodiversidad',
                'verbose_name_plural': 'Entradas de Biodiversidad',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('duration_info', models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, verbose_name='información de duración')),
                ('difficulty', models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, verbose_name='dificultad')),
                ('icon', models.CharField(default='🌿', help_text='Emoji representativo', max_length=10, verbose_name='ícono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences_tours_activities/', verbose_name='imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('question', models.CharField(max_length=300, verbose_name='pregunta')),
                ('answer', models.TextField(verbose_name='respuesta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(upload_to='gallery_homepage/', verbose_name='imagen')),
                ('is_hero', models.BooleanField(default=False, help_text='Usar como imagen principal en el hero', verbose_name='imagen hero')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
