# Generated by Django 5.2.10 on 2026-01-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversityentry',
            name='conservation_status_de',
            field=models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, null=True, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='conservation_status_en',
            field=models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, null=True, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='conservation_status_es',
            field=models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, null=True, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='conservation_status_fr',
            field=models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, null=True, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='conservation_status_it',
            field=models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, null=True, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='conservation_status_pt',
            field=models.CharField(blank=True, help_text='Ej: En peligro, Vulnerable, Preocupación menor', max_length=100, null=True, verbose_name='estado de conservación'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='description_de',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='description_en',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='description_es',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='description_it',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre común'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre común'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre común'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre común'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre común'),
        ),
        migrations.AddField(
            model_name='biodiversityentry',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre común'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_de',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_es',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_it',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty_de',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, null=True, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty_en',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, null=True, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty_es',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, null=True, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty_fr',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, null=True, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty_it',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, null=True, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty_pt',
            field=models.CharField(blank=True, help_text="Ej: 'Fácil', 'Moderado', 'Exigente'", max_length=50, null=True, verbose_name='dificultad'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_info_de',
            field=models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, null=True, verbose_name='información de duración'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_info_en',
            field=models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, null=True, verbose_name='información de duración'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_info_es',
            field=models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, null=True, verbose_name='información de duración'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_info_fr',
            field=models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, null=True, verbose_name='información de duración'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_info_it',
            field=models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, null=True, verbose_name='información de duración'),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_info_pt',
            field=models.CharField(blank=True, help_text="Ej: 'Medio día', '2-3 horas', 'Día completo'", max_length=100, null=True, verbose_name='información de duración'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_it',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_pt',
            field=models.TextField(null=True, verbose_name='respuesta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=300, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=300, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_it',
            field=models.CharField(max_length=300, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_pt',
            field=models.CharField(max_length=300, null=True, verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_it',
            field=models.CharField(max_length=100, null=True, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='título'),
        ),
    ]
