# Generated by Django 5.2.10 on 2026-01-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_count', models.PositiveIntegerField(default=180, help_text='Número inicial del contador', verbose_name='contador base')),
                ('inquiry_count', models.PositiveIntegerField(default=0, help_text='Número de formularios enviados', verbose_name='consultas recibidas')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador de Visitantes',
                'verbose_name_plural': 'Contador de Visitantes',
            },
        ),
        migrations.CreateModel(
            name='VisitorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='país')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='fecha estimada de llegada')),
                ('estimated_departure', models.DateField(blank=True, null=True, verbose_name='fecha estimada de salida')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='número de personas')),
                ('number_of_children', models.PositiveIntegerField(default=0, help_text='Menores de 18 años', verbose_name='número de menores')),
                ('services', models.JSONField(default=list, help_text='Lista de servicios de interés', verbose_name='servicios seleccionados')),
                ('special_requests', models.TextField(blank=True, help_text='Alergias, necesidades especiales, preguntas, etc.', verbose_name='solicitudes especiales')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, help_text='Notas del equipo de la comunidad', verbose_name='notas internas')),
                ('whatsapp_notified', models.BooleanField(default=False, verbose_name='notificado por WhatsApp')),
                ('email_notified', models.BooleanField(default=False, verbose_name='notificado por email')),
                ('source_language', models.CharField(default='es', max_length=5, verbose_name='idioma de origen')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'Consulta de Visitante',
                'verbose_name_plural': 'Consultas de Visitantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
