# Generated by Django 5.2.10 on 2026-01-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('notification_type', models.CharField(choices=[('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='tipo')),
                ('recipient', models.CharField(help_text='Email o número de teléfono', max_length=200, verbose_name='destinatario')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='asunto')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='estado')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado en')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='visitors.visitorinquiry', verbose_name='consulta')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
